//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.T
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Задание.
    /// </summary>
    // *** Start programmer edit section *** (Задание CustomAttributes)

    // *** End programmer edit section *** (Задание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаданиеE", new string[] {
            "Дата as \'Дата\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудник.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаданиеE", "Пункт", "ПунктE", true, "", "Пункт", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаданиеE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаданиеL", new string[] {
            "Дата as \'Дата\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    public class Задание : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.T.Сотрудник fСотрудник;
        
        private IIS.T.DetailArrayOfПункт fПункт;
        
        // *** Start programmer edit section *** (Задание CustomMembers)

        // *** End programmer edit section *** (Задание CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Задание.Дата CustomAttributes)

        // *** End programmer edit section *** (Задание.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Задание.Дата Get start)

                // *** End programmer edit section *** (Задание.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Задание.Дата Get end)

                // *** End programmer edit section *** (Задание.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.Дата Set start)

                // *** End programmer edit section *** (Задание.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Задание.Дата Set end)

                // *** End programmer edit section *** (Задание.Дата Set end)
            }
        }
        
        /// <summary>
        /// Задание.
        /// </summary>
        // *** Start programmer edit section *** (Задание.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Задание.Сотрудник CustomAttributes)
        [NotNull()]
        public virtual IIS.T.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Задание.Сотрудник Get start)

                // *** End programmer edit section *** (Задание.Сотрудник Get start)
                IIS.T.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Задание.Сотрудник Get end)

                // *** End programmer edit section *** (Задание.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.Сотрудник Set start)

                // *** End programmer edit section *** (Задание.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Задание.Сотрудник Set end)

                // *** End programmer edit section *** (Задание.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Задание.
        /// </summary>
        // *** Start programmer edit section *** (Задание.Пункт CustomAttributes)

        // *** End programmer edit section *** (Задание.Пункт CustomAttributes)
        public virtual IIS.T.DetailArrayOfПункт Пункт
        {
            get
            {
                // *** Start programmer edit section *** (Задание.Пункт Get start)

                // *** End programmer edit section *** (Задание.Пункт Get start)
                if ((this.fПункт == null))
                {
                    this.fПункт = new IIS.T.DetailArrayOfПункт(this);
                }
                IIS.T.DetailArrayOfПункт result = this.fПункт;
                // *** Start programmer edit section *** (Задание.Пункт Get end)

                // *** End programmer edit section *** (Задание.Пункт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Задание.Пункт Set start)

                // *** End programmer edit section *** (Задание.Пункт Set start)
                this.fПункт = value;
                // *** Start programmer edit section *** (Задание.Пункт Set end)

                // *** End programmer edit section *** (Задание.Пункт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаданиеE", typeof(IIS.T.Задание));
                }
            }
            
            /// <summary>
            /// "ЗаданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаданиеL", typeof(IIS.T.Задание));
                }
            }
        }
    }
}
